FROM zenika/alpine-maven

RUN apk update && apk upgrade && apk add --no-cache bash git openssh && apk add --update nodejs nodejs-npm
COPY equivalencia-front.sh /usr/src/app/
CMD  /usr/src/app/equivalencia-front.sh